distribution_code_name: Squirrel
distribution_name: "鼠鬚管"
distribution_version: 0.15.2
install_time: "Thu May 20 15:25:09 2021"
installation_id: "macOS"
rime_version: 1.7.3
sync_dir: "/Users/xh/OneDrive/config/rime/RimeData"
